swagger: '2.0'
info:
  description: >-
    Swagger definition file for gsalloc. gsalloc is a Node.js service providing
    a REST API to manage game server reservation for online games. 
  version: 1.0.0
  title: gsalloc
  contact:
    email: contact@xi4.me
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /gsalloc
tags:
  - name: server
    description: Everything related to game servers
schemes:
  - http
paths:
  /server/register:
    post:
      tags:
        - server
      summary: Registers server at service
      description: ''
      operationId: addServer
      produces:
        - application/json
      parameters:
        - name: server_ip
          in: query
          description: IPv4 address of gameserver
          required: true
          type: string
        - name: server_port
          in: query
          description: Port of gameserver
          required: true
          type: integer
      responses:
        '200':
          description: Server was successfully registered.
        '500':
          description: Server could not be registered.  
    delete:
      tags:
        - server
      summary: Unregisters server at service.
      description: ''
      operationId: unregisterServer
      produces:
        - application/json
      parameters:
        - name: server_id
          in: header
          description: ID of the Server that is being unregistered. Must be unique.
          required: true
          type: string
      responses:
        '200':
          description: Server was successfully unregistered.
        '404':
          description: No Server found that can be unregistered.
        '500':
          description: Server could not be unregistered.
  /server/ready:
    post:
      tags:
        - server
      summary: Sets Server ready status
      description: ''
      operationId: setReady
      produces:
        - application/json
      parameters:
        - name: server_id
          in: query
          description: ID of the Server that is being set ready. Must be unique.
          required: true
          type: string
      responses:
        '200':
          description: Server was successfully set ready.
        '500':
          description: Server could not be set ready.
  /server/reset:
    post:
      tags:
        - server
      summary: Resets server status
      description: ''
      operationId: resetServer
      produces:
        - application/json
      parameters:
        - name: server_id
          in: query
          description: ID of the Server that is being reset. Must be unique.
          required: true
          type: string
      responses:
        '200':
          description: Server was successfully reset.
        '500':
          description: Server could not be reset.  
  /client/register:
    post:
      tags:
        - client
      summary: Registers a client at gsalloc.
      description: ''
      operationId: registerClient
      produces:
        - application/json
      parameters:
        - name: client_customid
          in: header
          description: ID of client.
          required: false
          type: string
      responses:
        '200':
          description: Successfully registered.
          schema:
            $ref: '#/definitions/Client'
        '500':
          description: An error occured when trying to register the player.
  /client/alloc:
    get:
      tags:
        - client
      summary: Requests an available server that is currently registered.
      description: ''
      operationId: allocServer
      produces:
        - application/json
      parameters:
        - name: client_id
          in: header
          description: Real ID of Player that wants to request the server.
          required: false
          type: string
        - name: client_customid
          in: header
          description: Custom ID of Player that wants to request the server.
          required: false
          type: string
      responses:
        '200':
          description: A GameServer object.
          schema:
            $ref: '#/definitions/GameServer'
        '404':
          description: No free Server available.
        '500':
          description: An error occured when trying to allocate a server.
    delete:
      tags:
        - client
      summary: Stops a server request
      description: ''
      operationId: deallocServer
      produces:
        - application/json
      parameters:
        - name: client_id
          in: header
          description: Real ID of Player that wants to request the server.
          required: false
          type: string
        - name: client_customid
          in: header
          description: Custom ID of Player that wants to request the server.
          required: false
          type: string
      responses:
        '200':
          description: Request was successfully canceled.
        '404':
          description: Could no longer cancel request.
        '500':
          description: An error occured when trying to cancel the request.
  /client/ready:
    get:
      tags:
        - client
      summary: Requests the current ready status of a Server.
      description: ''
      operationId: getReadyStatus
      produces:
        - application/json
      parameters:
        - name: server_id
          in: header
          description: ID of Server which should be queried.
          required: true
          type: string
      responses:
        '200':
          description: A Gameserver object.
          schema:
            $ref: '#/definitions/GameServer'
        '404':
          description: No matching Server found.
        '500':
          description: An error occured when trying to query a server.
  /party/create:
    post:
      tags:
        - party
      summary: Creates a new party
      description: ''
      operationId: createParty
      produces:
        - application/json
      parameters:
        - name: party_slots
          in: header
          description: Amount of players to fill this party with
          required: true
          type: integer
      responses:
        '200':
          description: A Party Object
          schema:
            $ref: '#/definitions/Party'
        '500':
          description: An error occured when trying to create a party.
  /party/clients:
    post:
      tags:
        - party
      summary: Adds a client ID to a party
      description: ''
      operationId: addPartyClient
      produces:
        - application/json
      parameters:
        - name: party_id
          in: header
          description: ID of the Party.
          required: true
          type: string
        - name: client_id
          in: header
          description: Real ID of Player that wants to request the server.
          required: false
          type: string
        - name: client_customid
          in: header
          description: Custom ID of Player that wants to request the server.
          required: false
          type: string
      responses:
        '200':
          description: Successfully added the client to the party
          schema:
            $ref: '#/definitions/Party'
        '404':
          description: Could not find either the Party or Client ID in the database.
        '500':
          description: An error occured when trying to add a client to a party.
    delete:
      tags:
        - party
      summary: Deletes a client ID to a party
      description: ''
      operationId: deletePartyClient
      produces:
        - application/json
      parameters:
        - name: party_id
          in: header
          description: ID of the Party.
          required: true
          type: string
        - name: client_id
          in: header
          description: Real ID of Player that wants to request the server.
          required: false
          type: string
        - name: client_customid
          in: header
          description: Custom ID of Player that wants to request the server.
          required: false
          type: string
      responses:
        '200':
          description: Successfully removed the client from the party
          schema:
            $ref: '#/definitions/Party'
        '404':
          description: Could not find either the Party or Client ID in the database.
        '500':
          description: An error occured when trying to remove a client from a party.
    get:
      tags:
        - party
      summary: Gets all clients in a party
      description: ''
      operationId: getPartyClients
      produces:
        - application/json
      parameters:
        - name: party_id
          in: header
          description: ID of the Party.
          required: true
          type: integer
      responses:
        '200':
          description: A Party Object
          schema:
            $ref: '#/definitions/Party'
        '404':
          description: Could not find the Party ID in the database.
        '500':
          description: An error occured when trying to get the Party information.
definitions:
  GameServer:
    type: object
    properties:
      SERVER_id:
        type: string
      SERVER_ip:
        type: string
      SERVER_port:
        type: integer
      SERVER_ownerid:
        type: string
      SERVER_isReady:
        type: boolean
  Client:
    type: object
    properties:
      CLIENT_id:
        type: string
      CLIENT_customid:
        type: string
  Party:
    type: object
    properties:
      PARTY_id:
        type: string
      PARTY_slots:
        type: integer
      PARTY_clients:
        type: array
        items:
          $ref: '#/definitions/Client'